name: campusbite
description: Campus Food Delivery App with AI Chatbot
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.24.0  # Upgraded for null safety
  firebase_auth: ^4.13.0  # Upgraded for latest features
  cloud_firestore: ^4.8.4  # Upgraded for better performance
  firebase_storage: ^11.5.0  # Upgraded
  firebase_messaging: ^14.6.5  # Upgraded for FCM
  firebase_analytics: ^10.7.0  # Added for tracking
  google_sign_in: ^6.1.14

  # AI & Chatbot
  http: ^1.2.1  # More stable version
  dio: ^5.4.3  # Bugfix version
  markdown: ^7.2.5  # Updated for better parsing
  flutter_markdown: ^0.6.15  # Added for rendering
  json_annotation: ^4.8.1  # For API responses

  # UI
  google_fonts: ^6.3.0  # Latest stable
  cached_network_image: ^3.3.0  # Optimized version
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  badges: ^3.0.3  # Updated
  lottie: ^3.1.0  # Added for animations

  # Location
  geolocator: ^11.1.0  # More accurate
  google_maps_flutter: ^2.5.1  # Bugfix version
  geocoding: ^2.1.1  # Added for address lookup

  # Biometrics
  local_auth: ^2.1.8  # More stable
  local_auth_android: ^2.1.8  # Platform specific
  local_auth_ios: ^2.1.8  # Platform specific
  flutter_secure_storage: ^8.2.0  # Updated

  # Payments
  flutterwave_standard: ^1.2.0  # Updated
  mtn_momo: ^2.1.0  # Updated for Uganda
  airtel_money: ^1.3.0  # Updated for Uganda

  # State Management
  provider: ^6.1.5  # More stable
  flutter_riverpod: ^2.4.11  # Updated
  riverpod_annotation: ^2.3.1  # Added for codegen

  # Utilities
  intl: ^0.18.1  # More stable
  flutter_local_notifications: ^15.2.0  # Updated
  url_launcher: ^6.2.1  # Updated
  image_picker: ^1.0.7  # Updated
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  uuid: ^3.0.7
  flutter_dotenv: ^5.1.0  # Added for API keys

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Updated linter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1  # For JSON handling
  riverpod_generator: ^2.3.1  # For Riverpod codegen

flutter:
  uses-material-design: true
  generate: true  # Enable code generation
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - assets/lottie/
    - .env  # For environment variables

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  # Android configuration
  android:
    compileSdkVersion: 34
    minSdkVersion: 23
    targetSdkVersion: 34
    multiDexEnabled: true

  # iOS configuration
  ios:
    deploymentTarget: '13.0'