name: campusbite
description: Campus Food Delivery App with AI Chatbot
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Supabase (Replaces Firebase)
  supabase_flutter: ^1.10.6

  # AI & Chatbot
  http: ^1.2.1
  dio: ^5.4.3
  markdown: ^7.2.5
  flutter_markdown: ^0.6.15
  json_annotation: ^4.8.1

  # UI
  google_fonts: ^6.3.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  badges: ^3.0.3
  lottie: ^3.1.0

  # Location
  geolocator: ^11.1.0
  google_maps_flutter: ^2.5.1
  geocoding: ^2.1.1
  geofencing: ^2.0.0
  background_fetch: ^0.8.1

  # Biometrics
  local_auth: ^2.1.8
  local_auth_android: ^2.1.8
  local_auth_ios: ^2.1.8
  flutter_secure_storage: ^8.2.0

  # Payments
  flutterwave_standard: ^1.2.0
  mtn_momo: ^2.1.0
  airtel_money: ^1.3.0

  # USSD Services
  ussd_service: ^0.1.1
  telephony: ^0.2.1

  # State Management
  provider: ^6.1.5
  flutter_riverpod: ^2.4.11
  riverpod_annotation: ^2.3.1

  # Utilities
  intl: ^0.18.1
  flutter_local_notifications: ^15.2.0
  url_launcher: ^6.2.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  uuid: ^3.0.7
  flutter_dotenv: ^5.1.0
  timezone: ^0.9.2
  flutter_timezone: ^2.0.1

  # Mood Notifications
  mood_plugin: ^1.2.0
  pedometer: ^2.1.0
  sensors_plus: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - assets/lottie/
    - .env
    - assets/notificationsounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
